// https://www.figma.com/file/lwGToAET7pKxC3mpvOIBKa/prototypes?node-id=139%3A2
// https://www.figma.com/file/lwGToAET7pKxC3mpvOIBKa/prototypes?node-id=140%3A2

export default [
  {
    artist: "Monet",
    artworks: [
      {
        femmeGarment: "#A09DBF",
        femmeShoes: "#F4F4EA",
        filepath: "monet1.jpg",
        neutralGarment: "#BBB4F5",
        neutralShoes: "#C5C5C7",
        title: "Water Lilies I",
      },
      {
        femmeGarment: "#8BB6BC",
        femmeShoes: "#F4F4EA",
        filepath: "monet2.jpg",
        neutralGarment: "#C4DFDD",
        neutralShoes: "#C5C5C7",
        title: "Woman with a Parasol",
      },
      {
        femmeGarment: "#C099A1",
        femmeShoes: "#AEA183",
        filepath: "monet3.jpg",
        neutralGarment: "#D62424",
        neutralShoes: "#E8D39E",
        title: "Jeune fille dans le jardin de Giverny",
      },
      {
        femmeGarment: "#8BB6BC",
        femmeShoes: "#F4F4EA",
        filepath: "monet4.jpg",
        neutralGarment: "#C4DFDD",
        neutralShoes: "#C5C5C7",
        title: "Water Lilies II",
      },
      {
        femmeGarment: "#8DB6E4",
        femmeShoes: "#F4F4EA",
        filepath: "monet5.jpg",
        neutralGarment: "#B5E4FE",
        neutralShoes: "#E8D39E",
        title: "Antibes from la Salis",
      },
      {
        femmeGarment: "#A09DBF",
        femmeShoes: "#AEA183",
        filepath: "monet6.jpg",
        neutralGarment: "#BBB4F5",
        neutralShoes: "#7D5A46",
        title: "The Artist’s Garden at Giverny",
      },
    ],
  },
  {
    artist: "O’Keeffe",
    artworks: [
      {
        femmeGarment: "#8DB6E4",
        femmeShoes: "#F9F9F9",
        filepath: "okeeffe1.jpg",
        neutralGarment: "#B5E4FE",
        neutralShoes: "#F9F9F9",
        title: "Jimson Weed",
      },
      {
        femmeGarment: "#A09DBF",
        femmeShoes: "#F9F9F9",
        filepath: "okeeffe2.jpg",
        neutralGarment: "#BBB4F5",
        neutralShoes: "#F9F9F9",
        title: "Black Iris",
      },
      {
        femmeGarment: "#F58299",
        femmeShoes: "#F9F9F9",
        filepath: "okeeffe3.jpg",
        neutralGarment: "#F8B3C1",
        neutralShoes: "#F9F9F9",
        title: "Music, Pink and Blue No. 2",
      },
      {
        femmeGarment: "#8DB6E4",
        femmeShoes: "#000001",
        filepath: "okeeffe4.jpg",
        neutralGarment: "#C4DFDD",
        neutralShoes: "#F9F9F9",
        title: "Abstraction Blue",
      },
      {
        femmeGarment: "#CB5C37",
        femmeShoes: "#000001",
        filepath: "okeeffe5.jpg",
        neutralGarment: "#DB6060",
        neutralShoes: "#F9F9F9",
        title: "Oriental Poppies",
      },
      {
        femmeGarment: "#79977F",
        femmeShoes: "#000001",
        filepath: "okeeffe6.jpg",
        neutralGarment: "#3E5A83",
        neutralShoes: "#F9F9F9",
        title: "Blue and Green Music",
      },
    ],
  },
  {
    artist: "Picasso",
    artworks: [
      {
        femmeGarment: "#449E83",
        femmeShoes: "#AEA183",
        filepath: "picasso1.jpg",
        neutralGarment: "#8EC4B1",
        neutralShoes: "#7D5A46",
        title: "Femme se Coiffant",
      },
      {
        femmeGarment: "#273B4E",
        femmeShoes: "#F4F4EA",
        filepath: "picasso2.jpg",
        neutralGarment: "#3E5A83",
        neutralShoes: "#F9F9F9",
        title: "Child with a Dove",
      },
      {
        femmeGarment: "#C099A1",
        femmeShoes: "#AEA183",
        filepath: "picasso3.jpg",
        neutralGarment: "#F8B3C1",
        neutralShoes: "#E8D39E",
        title: "Les Demoiselles d'Avignon",
      },
      {
        femmeGarment: "#273B4E",
        femmeShoes: "#AEA183",
        filepath: "picasso4.jpg",
        neutralGarment: "#3E5A83",
        neutralShoes: "#7D5A46",
        title: "The Old Guitarist",
      },
      {
        femmeGarment: "#273B4E",
        femmeShoes: "#F4F4EA",
        filepath: "picasso5.jpg",
        neutralGarment: "#767678",
        neutralShoes: "#F7F2DB",
        title: "Bust of Woman with Hat",
      },
      {
        femmeGarment: "#AEA183",
        femmeShoes: "#F4F4EA",
        filepath: "picasso6.jpg",
        neutralGarment: "#767678",
        neutralShoes: "#C5C5C7",
        title: "Girl with Mandolin",
      },
    ],
  },
  {
    artist: "Van Gogh",
    artworks: [
      {
        femmeGarment: "#A2D1BD",
        femmeShoes: "#F4F4EA",
        filepath: "vangogh1.jpg",
        neutralGarment: "#B1DC9C",
        neutralShoes: "#F9F9F9",
        title: "Green Wheat Fields, Auvers",
      },
      {
        femmeGarment: "#D0B15C",
        femmeShoes: "#F4F4EA",
        filepath: "vangogh2.jpg",
        neutralGarment: "#8EC4B1",
        neutralShoes: "#E8D39E",
        title: "Vase with Twelve Sunflowers",
      },
      {
        femmeGarment: "#8BB6BC",
        femmeShoes: "#F4F4EA",
        filepath: "vangogh3.jpg",
        neutralGarment: "#8EC4B1",
        neutralShoes: "#F9F9F9",
        title: "Almond Blossoms",
      },
      {
        femmeGarment: "#273B4E",
        femmeShoes: "#000000",
        filepath: "vangogh4.jpg",
        neutralGarment: "#8EC4B1",
        neutralShoes: "#F7F2DB",
        title: "Starry Night Over the Rhône",
      },
      {
        femmeGarment: "#253A75",
        femmeShoes: "#F4F4EA",
        filepath: "vangogh5.jpg",
        neutralGarment: "#3E5A83",
        neutralShoes: "#F9F9F9",
        title: "Starry Night",
      },
      {
        femmeGarment: "#8DB6E4",
        femmeShoes: "#AEA183",
        filepath: "vangogh6.jpg",
        neutralGarment: "#7DACD7",
        neutralShoes: "#E8D39E",
        title: "The Bedroom",
      },
    ],
  },
  {
    artist: "Warhol",
    artworks: [
      {
        femmeGarment: "#C099A1",
        femmeShoes: "#F4F4EA",
        filepath: "warhol1.jpg",
        neutralGarment: "#BBB4F5",
        neutralShoes: "#E8D39E",
        title: "Marilyn Monroe",
      },
      {
        femmeGarment: "#D0B15C",
        femmeShoes: "#F4F4EA",
        filepath: "warhol2.jpg",
        neutralGarment: "#DB6060",
        neutralShoes: "#F7F2DB",
        title: "Banana (F. & S. 10)",
      },
      {
        femmeGarment: "#C0679F",
        femmeShoes: "#000000",
        filepath: "warhol3.jpg",
        neutralGarment: "#FF800B",
        neutralShoes: "#F9F9F9",
        title: "Cantaloupes II",
      },
      {
        femmeGarment: "#BF142D",
        femmeShoes: "#F9F9F9",
        filepath: "warhol4.jpg",
        neutralGarment: "#DB6060",
        neutralShoes: "#C5C5C7",
        title: "Campbell's Soup Cans",
      },
      {
        femmeGarment: "#273B4E",
        femmeShoes: "#000000",
        filepath: "warhol5.jpg",
        neutralGarment: "#3E5A83",
        neutralShoes: "#C5C5C7",
        title: "Skull",
      },
      {
        femmeGarment: "#CB5C37",
        femmeShoes: "#000000",
        filepath: "warhol6.jpg",
        neutralGarment: "#FF800B",
        neutralShoes: "#F9F9F9",
        title: "Orange Car Crash Fourteen Times",
      },
    ],
  },
];
