export const ART_ADD = "ART_ADD";
export const CART_ADD = "CART_ADD";
export const NAVIGATOR_PAGE_SET = "NAVIGATOR_PAGE_SET";
export const NAVIGATOR_TAB_INCREMENT = "NAVIGATOR_TAB_INCREMENT";
export const NAVIGATOR_TAB_DECREMENT = "NAVIGATOR_TAB_DECREMENT";
export const NAVIGATOR_TAB_QUIT = "NAVIGATOR_TAB_QUIT";
export const ERRORS_CLEAR = "ERRORS_CLEAR";
export const ERRORS_GET = "ERRORS_GET";
